dist: bionic
language: minimal
env:
  - tag=19.10 aliases="eoan rolling"
  - tag=19.04 aliases="disco"
  - tag=18.04 aliases="bionic latest"
  - tag=16.04 aliases="xenial"
notifications:
  email: false

script:
  # build
  - docker build --build-arg tag=$tag -t dongzhuoer/ubuntu-cn:$tag .
  - for alias in $aliases; do docker tag dongzhuoer/ubuntu-cn:$tag dongzhuoer/ubuntu-cn:$alias; done
  # deploy
  - echo "$DOCKER_PASSWORD" | docker login -u dongzhuoer --password-stdin
  - docker push dongzhuoer/ubuntu-cn:$tag
  - for alias in $aliases; do docker push dongzhuoer/ubuntu-cn:$alias; done
  # test (to do: utf8)
  - docker run --rm dongzhuoer/ubuntu-cn:$tag bash -i -c "ls /usr/lib/x86_+([0-9])-* -d"
