language: generic
services: docker

script:
  # build
  - docker build -t dongzhuoer/ubuntu-cn .
  # deploy
  - echo "$DOCKER_PASSWORD" | docker login -u dongzhuoer --password-stdin
  - docker push dongzhuoer/ubuntu-cn
  # test
  - bash -e test.sh
notifications:
  email: false
