FROM ubuntu:latest

LABEL maintainer="Zhuoer Dong <dongzhuoer@mail.nankai.edu.cn>"

RUN sed -i 's/archive.ubuntu.com/mirrors4.tuna.tsinghua.edu.cn/' /etc/apt/sources.list
RUN sed -i 's/archive.canonical.com/mirrors4.tuna.tsinghua.edu.cn/' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors4.tuna.tsinghua.edu.cn/'   /etc/apt/sources.list
